steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - function-http-firestore
      - --entry-point=functions.UserFunction
      - --region=us-central1
      - --source=.
      - --trigger-http
      - --runtime=java17
      - --memory=512MB
      - --timeout=90
      - --min-instances=0
      - --max-instances=1
      - --allow-unauthenticated
      - --service-account=695188009723-compute@developer.gserviceaccount.com
      - --quiet
options:
  logging: CLOUD_LOGGING_ONLY